### ISSUE TITLE
Native module build failures are scary

### ISSUE THREAD

**Issue by JoeLudwig** [webaverse/xrpackage-cli#2]
When installing the tool with "npm install -g xrpk" I got hundreds of lines of spew, many of which are errors building native modules. This makes it look like the install has failed when it actually worked.

Here are some samples:
`  win_delay_load_hook.cc
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\keccak\src\addon.cc(37,1): error C2660: 'v8::Value::Int
egerValue': function does not take 0 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\keccak\
build\keccak.vcxproj]
C:\Users\Joe\AppData\Local\node-gyp\Cache\12.13.0\include\node\v8.h(2609,40): message : see declaration of 'v8::Value::
IntegerValue' (compiling source file ..\src\addon.cc) [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\
keccak\build\keccak.vcxproj]
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\keccak\src\addon.cc(38,1): error C2660: 'v8::Value::Int
egerValue': function does not take 0 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\keccak\
build\keccak.vcxproj]
C:\Users\Joe\AppData\Local\node-gyp\Cache\12.13.0\include\node\v8.h(2609,40): message : see declaration of 'v8::Value::
IntegerValue' (compiling source file ..\src\addon.cc) [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\
keccak\build\keccak.vcxproj]
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\keccak\src\addon.cc(56,1): error C2660: 'v8::Value::Int
egerValue': function does not take 0 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\keccak\
build\keccak.vcxproj]
C:\Users\Joe\AppData\Local\node-gyp\Cache\12.13.0\include\node\v8.h(2609,40): message : see declaration of 'v8::Value::
IntegerValue' (compiling source file ..\src\addon.cc) [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\
keccak\build\keccak.vcxproj]
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\keccak\src\addon.cc(64,1): error C2660: 'v8::Value::Int
egerValue': function does not take 0 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\keccak\
build\keccak.vcxproj]
C:\Users\Joe\AppData\Local\node-gyp\Cache\12.13.0\include\node\v8.h(2609,40): message : see declaration of 'v8::Value::
IntegerValue' (compiling source file ..\src\addon.cc) [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\
keccak\build\keccak.vcxproj]
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\keccak\src\addon.cc(75,1): error C2661: 'v8::Value::ToO
bject': no overloaded function takes 0 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\kecca
k\build\keccak.vcxproj]
[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mbuild error[0m
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m Error: `E:\ProgramFiles\Visual Studio 2019\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at ChildProcess.onExit (C:\Users\Joe\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at ChildProcess.emit (events.js:210:5)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mSystem[0m Windows_NT 10.0.18362
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mcommand[0m "d:\\ProgramFiles\\nodejs\\node.exe" "C:\\Users\\Joe\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mcwd[0m C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\keccak
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnode -v[0m v12.13.0
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnode-gyp -v[0m v5.0.5
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnot ok[0m
`

`C:\Users\Joe\AppData\Local\node-gyp\Cache\12.13.0\include\node\v8.h(5995,46): message : see declaration of 'v8::Functio
nTemplate::GetFunction' (compiling source file ..\src\bufferutil.cc) [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrp
k\node_modules\@web3-js\websocket\build\bufferutil.vcxproj]
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\@web3-js\websocket\src\bufferutil.cc(34,1): error C2661
: 'Nan::Set': no overloaded function takes 2 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules
\@web3-js\websocket\build\bufferutil.vcxproj]
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\@web3-js\websocket\src\bufferutil.cc(50,1): error C2661
: 'v8::Value::ToObject': no overloaded function takes 0 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\n
ode_modules\@web3-js\websocket\build\bufferutil.vcxproj]
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\@web3-js\websocket\src\bufferutil.cc(57,1): error C2661
: 'v8::Value::ToObject': no overloaded function takes 0 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\n
ode_modules\@web3-js\websocket\build\bufferutil.vcxproj]
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\@web3-js\websocket\src\bufferutil.cc(68,1): error C2661
: 'v8::Value::ToObject': no overloaded function takes 0 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\n
ode_modules\@web3-js\websocket\build\bufferutil.vcxproj]
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\@web3-js\websocket\src\bufferutil.cc(70,1): error C2661
: 'v8::Value::ToObject': no overloaded function takes 0 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\n
ode_modules\@web3-js\websocket\build\bufferutil.vcxproj]
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\@web3-js\websocket\src\bufferutil.cc(89,1): error C2661
: 'v8::Value::ToObject': no overloaded function takes 0 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\n
ode_modules\@web3-js\websocket\build\bufferutil.vcxproj]
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\@web3-js\websocket\src\bufferutil.cc(90,1): error C2661
: 'v8::Value::ToObject': no overloaded function takes 0 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\n
ode_modules\@web3-js\websocket\build\bufferutil.vcxproj]
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\@web3-js\websocket\src\bufferutil.cc(92,1): error C2661
: 'v8::Value::ToObject': no overloaded function takes 0 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\n
ode_modules\@web3-js\websocket\build\bufferutil.vcxproj]
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\@web3-js\websocket\src\bufferutil.cc(93,1): error C2660
: 'v8::Value::Int32Value': function does not take 0 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_
modules\@web3-js\websocket\build\bufferutil.vcxproj]
C:\Users\Joe\AppData\Local\node-gyp\Cache\12.13.0\include\node\v8.h(2613,40): message : see declaration of 'v8::Value::
Int32Value' (compiling source file ..\src\bufferutil.cc) [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modul
es\@web3-js\websocket\build\bufferutil.vcxproj]
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\@web3-js\websocket\src\bufferutil.cc(94,1): error C2660
: 'v8::Value::Int32Value': function does not take 0 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_
modules\@web3-js\websocket\build\bufferutil.vcxproj]
C:\Users\Joe\AppData\Local\node-gyp\Cache\12.13.0\include\node\v8.h(2613,40): message : see declaration of 'v8::Value::
Int32Value' (compiling source file ..\src\bufferutil.cc) [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modul
es\@web3-js\websocket\build\bufferutil.vcxproj]
  validation.cc
  win_delay_load_hook.cc
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\@web3-js\websocket\src\validation.cc(114,1): error C266
0: 'v8::FunctionTemplate::GetFunction': function does not take 0 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modul
es\xrpk\node_modules\@web3-js\websocket\build\validation.vcxproj]
C:\Users\Joe\AppData\Local\node-gyp\Cache\12.13.0\include\node\v8.h(5995,46): message : see declaration of 'v8::Functio
nTemplate::GetFunction' (compiling source file ..\src\validation.cc) [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrp
k\node_modules\@web3-js\websocket\build\validation.vcxproj]
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\@web3-js\websocket\src\validation.cc(114,1): error C266
1: 'Nan::Set': no overloaded function takes 2 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_module
s\@web3-js\websocket\build\validation.vcxproj]
C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\node_modules\@web3-js\websocket\src\validation.cc(133,1): error C266
1: 'v8::Value::ToObject': no overloaded function takes 0 arguments [C:\Users\Joe\AppData\Roaming\npm\node_modules\xrpk\
node_modules\@web3-js\websocket\build\validation.vcxproj]
`

**Comment by avaer** [comment]
Managed to shave off all of the native deps 🎉

**Comment by avaer** [comment]
Fixes as of `0.0.20`
