### ISSUE TITLE
xrpk wallet fails with "window is not defined"

### ISSUE THREAD

**Issue by shu8** [webaverse/xrpackage-cli#20]
Running `xrpk wallet` gives the following error:

```bash
$ xrpk wallet       
seed phrase (BIP39 format, default: auto):
ReferenceError: window is not defined
    at Function.Random.getRandomBufferBrowser (/mnt/c/Users/Shubham/Documents/GitHub/MLH/xrpackage-cli/eth-lightwallet.js:9025:3)
    at Function.Random.getRandomBuffer (/mnt/c/Users/Shubham/Documents/GitHub/MLH/xrpackage-cli/eth-lightwallet.js:9015:38)
    at Function.Mnemonic._mnemonic (/mnt/c/Users/Shubham/Documents/GitHub/MLH/xrpackage-cli/eth-lightwallet.js:23227:20)
    at new Mnemonic (/mnt/c/Users/Shubham/Documents/GitHub/MLH/xrpackage-cli/eth-lightwallet.js:23060:31)
    at Function.KeyStore.generateRandomSeed (/mnt/c/Users/Shubham/Documents/GitHub/MLH/xrpackage-cli/eth-lightwallet.js:465:12)
    at Object.yargs.scriptName.command.command.command.command [as handler] (/mnt/c/Users/Shubham/Documents/GitHub/MLH/xrpackage-cli/cli.js:820:41)
    at process._tickCallback (internal/process/next_tick.js:68:7) 
```

It looks like it's stemming from the `Random.getRandomBufferBrowser` method of [`eth-lightwallet.js`](https://github.com/webaverse/xrpackage-cli/blob/master/eth-lightwallet.js), which looks like it assumes a browser environment, I think:
```js
Random.getRandomBufferBrowser = function (size) {
  if (!window.crypto && !window.msCrypto) throw new Error('window.crypto not available');
  if (window.crypto && window.crypto.getRandomValues) var crypto = window.crypto;else if (window.msCrypto && window.msCrypto.getRandomValues) //internet explorer
    var crypto = window.msCrypto;else throw new Error('window.crypto.getRandomValues not available');
  var bbuf = new Uint8Array(size);
  crypto.getRandomValues(bbuf);
  var buf = Buffer.from(bbuf);
  return buf;
};
```

**Comment by avaer** [comment]
This looks like a legitimate bug.

We manually tried to node-ify `eth-lighwallet.js` but this was done manually on that massive file, and we might have missed some spots. It might be worth trying to redo the eth-lightwallet build from scratch again, without manual edits.

The main reason we do it this way is so that our CLI does not have any native dependencies on `npm install`.

**Comment by shu8** [comment]
I tried just using the latest version of https://github.com/ConsenSys/eth-lightwallet but got an error that `Buffer` isn't defined which is pretty weird. It does say it's for Node and the browser though, and I think I can see the import happening. 

Also, about the native dependencies -- I couldn't see which ones were needed?

**Comment by avaer** [comment]
On my system just `eth-lighwallet` causes a native build, which makes for a slow install experience for all dependencies from `npm`.

The `Buffer` bug looks like it is expecting some sort of build process to polyfill Buffer and things. I think the way I produced `eth-lighwallet.js` was using Parcel bundler to target `browser`, but it didn't do a complete job -- hence the manual patching that is now bugged.

It might make sense to try a Parcel build again (to get a single JS file) and figure out what was wrong in that bundling that it still had crashing references in the browser environment.

**Comment by shu8** [comment]
I tried it with Parcel but had no luck trying to do stuff like:

```
parcel build index.js --target node --bundle-node-modules
```

and I think we do want to be targeting `node` not `browser` because the code we're running in the CLI for eth-lightwallet is in the Node environment, not browser

But if I use Browserify with:

```
browserify index.js -o eth-lightwallet.bundle.js --node --standalone ethlightwallet
```

and also do a find+replace for `new Buffer` => `Buffer.from`, it seems to work.

**Comment by shu8** [comment]
I made a PR for what I found yesterday at https://github.com/webaverse/xrpackage-cli/pull/29
